services:
  salt:
    build: .
    container_name: server-salt
    privileged: true
    volumes:
      - ./salt/states:/srv/salt:ro
      - ./salt/pillar:/srv/pillar:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
