services:
  salt:
    build: .
    container_name: server-salt
    privileged: true
    cgroup: host
    ports:
      - "2222:22"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
